package com.geekhub.enums;

public enum AgeCategorie {
    PRESCHOOLERS,
    PRESCHOOLERS_PROFESSIONALS,
    JUNIOR_CLASSES,
    JUNIOR_CLASSES_PROFESSIONALS,
    MIDDLE_CLASSES,
    MIDDLE_CLASSES_PROFESSIONALS,
    HIGH_SCHOOL,
    HIGH_SCHOOL_PROFESSIONALS,
    ADULTS,
    ADULTS_PROFESSIONALS
}
